GET https://api.themoviedb.org/3/movie/popular?page=2 HTTP/1.1

Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjYzZlN2I3OTJjM2YzOTY4YTc0MWNkNGJlNTY4NmNlNCIsInN1YiI6IjY1MjAzMTlhNzQ1MDdkMDBmZjk5MzkyNSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.FJCAiSCe3KDik5MOQC5iF9VBaOHqcZ2wXuMODMCIJr4

GET https://api.themoviedb.org/3/configuration HTTP/1.1

Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjYzZlN2I3OTJjM2YzOTY4YTc0MWNkNGJlNTY4NmNlNCIsInN1YiI6IjY1MjAzMTlhNzQ1MDdkMDBmZjk5MzkyNSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.FJCAiSCe3KDik5MOQC5iF9VBaOHqcZ2wXuMODMCIJr4


GET hhtps://api.themoviedb.org/3/search/movie?query=spiderman HTTP/1.1

Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjYzZlN2I3OTJjM2YzOTY4YTc0MWNkNGJlNTY4NmNlNCIsInN1YiI6IjY1MjAzMTlhNzQ1MDdkMDBmZjk5MzkyNSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.FJCAiSCe3KDik5MOQC5iF9VBaOHqcZ2wXuMODMCIJr4


GET https://api.themoviedb.org/3/movie/787699 HTTP/1.1

Authorization:  Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjYzZlN2I3OTJjM2YzOTY4YTc0MWNkNGJlNTY4NmNlNCIsInN1YiI6IjY1MjAzMTlhNzQ1MDdkMDBmZjk5MzkyNSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.FJCAiSCe3KDik5MOQC5iF9VBaOHqcZ2wXuMODMCIJr4